### ISSUE TITLE
Music does not resume playing after call has ended

### ISSUE THREAD

**Issue by umarniz** [Gruveo/gruveo-ios-sdk#8]
When I play music on device, it pauses during the call, but doesn't continue after the call. Spotify is also not the active music player anymore so I can't press play from the action-center on iOS.

Steps to reproduce:

1) Play Spotify music
2) Initiate video call
3) End video call

Expected behaviour would be that Spotify resumes playing.

**Comment by artmatsak** [comment]
Sorry for the delay in updating this - the issue has already been fixed internally and the fix will be released in the next SDK version.

**Comment by umarniz** [comment]
@artmatsak any update on this?

**Comment by artmatsak** [comment]
Almost there, sorry for the delay!

**Comment by artmatsak** [comment]
@umarniz We have released version 1.3 of the SDK, where this issue should be fixed.

**Comment by xaviraol** [comment]
Hello @artmatsak , I'm working with @umarniz .
It appears this is still not working in our end. We are using our [react-native-gruveo](https://github.com/senseobservationsystems/react-native-gruveo) and we are still experiencing two problems using `gruveo-ios-sdk 1.3`:

- Launching the app while music playing: The music is paused.
- Initiating the call while playing music: The music stops and to restart and doesn't resume after the call is finished.

**Comment by artmatsak** [comment]
Sorry for the delay, we are looking to this.

**Comment by freakinruben** [comment]
Hi @artmatsak, any update on this?

**Comment by artmatsak** [comment]
I'm afraid we haven't had any luck with this so far. The WebRTC library's sound routing is quite opaque on iOS and we don't always have granular control. I will update the issue should we manage to make progress with this.
